
package UserController;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import main.databaseSQL;
import main.EveryTime_Main;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import main.databaseSQL;
import main.EveryTime_Main;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableModel;
public class PostController extends databaseSQL implements MouseListener, KeyListener,ListSelectionListener {
    String bt3;
    static String AA;
    DefaultListModel model3 = new DefaultListModel();
    public PostController() {
          initComponents();
        dbLoad();
        
        //String userNum = EveryTime_Main.UserNum; //사용자 번호 
        //String post_Num = EveryTime_Main.PostNum;   // 게시글 번호
        String userNum = "00001";
        String post_Num ="00001";
        String title = "postTitle";
        String post = "post";
        String postNum = "postNum"; 
        String postcontent = "postContent";
        String comment = "comContent";
        String writer = "userNum";

        // 제목 출력
        try{
            String  postTitle = returnData(post, title , postNum, post_Num);
            PostTitle.setText(postTitle);
            PostTitle.disable();

        }catch(SQLException ex){
            Logger.getLogger(BoardController.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      //  내용 출력
        try{
            String  postContent = returnData(post, postcontent, postNum, post_Num);
            PostContent.setText(postContent);
            PostContent.disable();
        }catch(SQLException ex){
            Logger.getLogger(BoardController.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        
        // 댓글 출력은 아직 구현 덜함..
        DefaultListModel model = new DefaultListModel();
        try{
            String result = returnComment(writer, comment, post_Num);
            System.out.print(result);
            
            
           /*ArrayList<String> stData = getStatus();
            
            for(int i=0; i < stData.size(); i++){
                String list[] = stData.get(i).split("\n");
                System.out.print(list[i]);
                model.addElement(list[i]);
                CommentList.setModel(model); // 화면에 보이게 
                if(list[i] == null){ break; } }*/
            }
            
                      
        catch(SQLException ex){
            Logger.getLogger(BoardController.class.getName()).log(Level.SEVERE, null, ex);
        }
        dbClose();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        PostContent = new javax.swing.JTextArea();
        Register = new javax.swing.JButton();
        Comment = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        Recommend = new javax.swing.JButton();
        Report = new javax.swing.JButton();
        PostTitle = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        CommentList = new javax.swing.JTable();
        Alarm = new javax.swing.JToggleButton();
        SendMessage = new javax.swing.JButton();
        CountReco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("휴먼편지체", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Everytime");

        jLabel2.setFont(new java.awt.Font("맑은 고딕", 0, 15)); // NOI18N
        jLabel2.setText("게시글");

        PostContent.setColumns(20);
        PostContent.setRows(5);
        PostContent.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                PostContentInputMethodTextChanged(evt);
            }
        });
        jScrollPane2.setViewportView(PostContent);

        Register.setBackground(new java.awt.Color(153, 0, 0));
        Register.setFont(new java.awt.Font("맑은 고딕", 0, 15)); // NOI18N
        Register.setForeground(new java.awt.Color(255, 255, 255));
        Register.setText("등록");
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });

        Comment.setFont(new java.awt.Font("맑은 고딕", 0, 15)); // NOI18N
        Comment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommentActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        back.setText("뒤로가기");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        Recommend.setText("👍");
        Recommend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecommendActionPerformed(evt);
            }
        });

        Report.setForeground(new java.awt.Color(153, 0, 0));
        Report.setText("🚨");
        Report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportActionPerformed(evt);
            }
        });

        PostTitle.setFont(new java.awt.Font("맑은 고딕", 0, 20)); // NOI18N
        PostTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostTitleActionPerformed(evt);
            }
        });

        CommentList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(CommentList);

        Alarm.setText("🔔");
        Alarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlarmActionPerformed(evt);
            }
        });

        SendMessage.setText("✉");
        SendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendMessageActionPerformed(evt);
            }
        });

        CountReco.setFont(new java.awt.Font("맑은 고딕", 0, 15)); // NOI18N

        jLabel3.setText("👍");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Comment)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Register, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(PostTitle)
                        .addComponent(jScrollPane2)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CountReco))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(232, 232, 232)
                                .addComponent(back))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SendMessage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Alarm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Report)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Recommend)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(back))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CountReco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(Alarm, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Recommend, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Report, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SendMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PostTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Comment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Register))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // 뒤로가기
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void RecommendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecommendActionPerformed
       //추천 Recommend
        dbLoad();
        String userNum = EveryTime_Main.UserNum;    // 사용자
        //String post_Num = EveryTime_Main.PostNum;   // 게시글 번호
        String post_Num = "00001";
        String rd = "recommend";  // 추천수
        
        try{
            int recommend = returnRecommend(rd, post_Num);   // 추천수 얻어오기
            System.out.println(recommend);
            recommend = recommend + 1;
            updatePost(post_Num, recommend);    // 추천눌렀을때 원래 값에서 +1되도록
            
            Recommend.setEnabled(false);    // 버튼 비활성화
        }catch(SQLException ex){
            Logger.getLogger(BoardController.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "[ 이 글을 추천하였습니다. ]", "메세지", JOptionPane.INFORMATION_MESSAGE);

        dbClose();
        // TODO add your handling code here:

    }//GEN-LAST:event_RecommendActionPerformed

    private void ReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportActionPerformed
                                             
        // 신고 _ 자신의 글일땐 버튼이 안보이도록
        /*
        senderNum : 송신자 고유 번호 (CHAR)
        receiverNum : 수신자 고유 번호 (CHAR)
        noticeDate : 알림 수신 일자 (DATETIME)
        noticeType : 댓글/추천/쪽지 등 타입 (VARCHAR)
        noticeContent : 알림 내용 (VARCHAR)
        */

        dbLoad();
        String userNum = EveryTime_Main.UserNum; //사용자 번호
        String postNum = EveryTime_Main.PostNum;   // 게시글 번호

        /*try{
            
        }catch(SQLException ex){
            Logger.getLogger(BoardController.class.getName()).log(Level.SEVERE, null, ex);
        }*/

       JOptionPane.showMessageDialog(this, "[ 이 글을 신고하였습니다. ]", "메세지", JOptionPane.INFORMATION_MESSAGE);
        dbClose();
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(this, "[ 이 글을 신고하였습니다. ]", "메세지", JOptionPane.INFORMATION_MESSAGE);

        // TODO add your handling code here:
    }//GEN-LAST:event_ReportActionPerformed

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
         // 댓글 등록
        dbLoad();
        String comment = Comment.getText(); // 댓글 내용
        //String userNum = EveryTime_Main.UserNum; //사용자 번호 
        //String postNum = EveryTime_Main.PostNum;   // 게시글 번호
        String userNum = "00001"; // 사용자 테스트번호 
        String postNum = "00001"; // 게시글 테스트번호
                
        if(comment.replaceAll("[^a-zA-Zㄱ-힣]", "").length() == 0){
             JOptionPane.showMessageDialog(this, "[ 내용을 입력하세요 ]", "메세지", JOptionPane.INFORMATION_MESSAGE);
        }else{ // 댓글 등록 되도록
            try{
                postComment(postNum, userNum, comment);
                // 게시글 번호, 사용자 번호, 댓글 번호
            }catch(SQLException ex){
            Logger.getLogger(BoardController.class.getName()).log(Level.SEVERE, null, ex);
        } 
            JOptionPane.showMessageDialog(this, "[ 댓글이 등록되었습니다. ]", "메세지", JOptionPane.INFORMATION_MESSAGE);
            
        }
        dbClose();
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterActionPerformed

    private void PostTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostTitleActionPerformed
        // 게시글 제목 나타내기
        dbLoad();
        String userNum = EveryTime_Main.UserNum; //사용자 번호 
        String post_Num = EveryTime_Main.PostNum;   // 게시글 번호
       // String post_Num = "00001";
        String title = "boardTitle";
        String table = "post";
        String postNum = "postNum";
        String msgbox;
        try{
            //String  postcontent = returnData(title, table, postNum, post_Num);
            msgbox = "123";
            System.out.println("123");
            PostTitle.setText(msgbox);
            
        }catch(Exception e){
        }
        dbClose();
        // TODO add your handling code here:
    }//GEN-LAST:event_PostTitleActionPerformed

    private void CommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommentActionPerformed
        // 댓글 작성란
        // TODO add your handling code here:
    }//GEN-LAST:event_CommentActionPerformed

    private void PostContentInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_PostContentInputMethodTextChanged
        // TODO add your handling code here:
        dbLoad();
        String userNum = EveryTime_Main.UserNum; //사용자 번호 
        String post_Num = EveryTime_Main.PostNum;   // 게시글 번호
        //String post_Num = "00001";
        String table = "post";  
        String content = "postContent";
        String postNum = "postNum";
        PostContent.isEditable();

        try{
            String  postcontent = returnData(content, table, postNum, post_Num);
            PostContent.setText(postcontent);
            
        }catch(Exception e){
        }
        dbClose();
    }//GEN-LAST:event_PostContentInputMethodTextChanged

    private void SendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendMessageActionPerformed
        // 쪽지 보내기 _ 자신의 글일때 버튼 안보이도록 
        


        // TODO add your handling code here:
    }//GEN-LAST:event_SendMessageActionPerformed

    private void AlarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlarmActionPerformed
          // 알람 버튼
        dbLoad();
        String userNum = EveryTime_Main.UserNum; //사용자 번호
        String postNum = EveryTime_Main.PostNum;   // 게시글 번호      

        ItemListener itemListener = new ItemListener() {
        public void itemStateChanged(ItemEvent itemEvent) {
            int state = itemEvent.getStateChange();
            // 왜 처음값 무시?????????
            // state > ON : 2 , OFF : 1
            initComponents();   // add 초기화
            
            if (state == ItemEvent.SELECTED) {  // 1
               System.out.println("OFF state : "+state);
               //JOptionPane.showMessageDialog(null, "[ 이글의 알람을 껐습니다. ]");
               //JOptionPane.showConfirmDialog(, "[ 이글의 알람을 껐습니다. ]", "메세지", JOptionPane.INFORMATION_MESSAGE);
               //JOptionPane.showMessageDialog(null,"[ 이 글의 알람을 껐습니다. ]", "메세지", JOptionPane.INFORMATION_MESSAGE);
               // DB 알람 끄도록...
            } else if(state == ItemEvent.DESELECTED) {    //2
                System.out.println("On state : "+state); // remove your message
                //JOptionPane.showMessageDialog(null, "[ 이글의 알람을 켰습니다. ]");
                //JOptionPane.showMessageDialog(null,"[ 이 글의 알람을 켰습니다. ]", "메세지", JOptionPane.INFORMATION_MESSAGE);
                // 다시 키기
            }
        }

            
    };
    Alarm.addItemListener(itemListener);
    
     dbClose();
        // TODO add your handling code here:


        
    }//GEN-LAST:event_AlarmActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //켜자마자 보여주는 화면
        dbLoad();
        //post 테이블을 불러옴
        //postTitle 불러옴
        //postContent,recommend 게시글내용과 추천수를 게시글내용에 추가하고 추천수는 가장위에 표시
        PostTitle.setText(bt3);
        java.sql.Statement stmt2 = null;
        try {
            stmt2 = conn.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(PostController.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            String sql = "select * from post where postTitle =  \"" + bt3 + "\" ";
            rs = stmt2.executeQuery(sql);
            while(rs.next()){
            String A =rs.getString("userNum");
            String B =rs.getString("postContent");
            AA = A;
            }
        } catch (SQLException ex) {
            Logger.getLogger(PostController.class.getName()).log(Level.SEVERE, null, ex);
        }
            PostContent.setText("");
       
        //comment 테이블을 불러옴
        //comContent,recommend 댓글내용과 댓글추천수를 불러옴.
        
        java.sql.Statement stmt3 = null;
        try {
            stmt3 = conn.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(PostController.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            String sql = "select * from comment where userNum =  \"" + AA + "\" ";
            rs = stmt3.executeQuery(sql);
        } catch (SQLException ex) {
            Logger.getLogger(PostController.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            while(rs.next()){
            model3.addElement(rs.getString("comContent"));
            CommentList.setModel((TableModel) model3);
            }
        } catch (SQLException ex) {
            Logger.getLogger(PostController.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        dbClose();
        
    }//GEN-LAST:event_formWindowOpened

    
    private void PostContentPerformed(java.awt.event.ActionEvent evt){
        // 게시글 내용 출력
        dbLoad();
        String table = "post";
        String content = "postContent";
        String postNum = "postNum";
        /*
        boardTitle : 게시판 이름 (VARCHAR)
        postNum : 게시글 번호 (CHAR)
        postTitle : 게시글 제목 (VARCHAR)
        postContent : 게시글 내용 (VARCHAR)
        userNum : 작성자 고유 번호 (CHAR)
        postDate : 작성 일자 (DATETIME)
        recommend : 추천 수 (INT)
        */
        String userNum = EveryTime_Main.UserNum; //사용자 번호 
        String post_Num = EveryTime_Main.PostNum;   // 게시글 번호        
        
        try{
            String boardTitle = returnData(content, table, postNum, post_Num);
            PostContent.setText(content);
        }catch(Exception e){
        }
        
        dbClose();
    }
    
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PostController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PostController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PostController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PostController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PostController().setVisible(true);
            }
        });
        
        //CommentList
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Alarm;
    private javax.swing.JTextField Comment;
    private javax.swing.JTable CommentList;
    private javax.swing.JTextField CountReco;
    private javax.swing.JTextArea PostContent;
    private javax.swing.JTextField PostTitle;
    private javax.swing.JButton Recommend;
    private javax.swing.JButton Register;
    private javax.swing.JButton Report;
    private javax.swing.JButton SendMessage;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mousePressed(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseExited(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void keyTyped(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void keyPressed(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void keyReleased(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
