/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserController;

import SingletonPattern.UserInfo;

public class SettingController extends javax.swing.JFrame {

    UserInfo userinfo = UserInfo.getInstance();
    /**
     * Creates new form SettingController
     */
    public SettingController() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SchoolConfirm = new javax.swing.JButton();
        ChangePW = new javax.swing.JButton();
        ChangeEmail = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        UserDelete = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        PremiumSet = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("휴먼편지체", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Everytime");

        jLabel2.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jLabel2.setText("설정");

        jLabel3.setFont(new java.awt.Font("맑은 고딕", 0, 15)); // NOI18N
        jLabel3.setText("[계정]");

        SchoolConfirm.setFont(new java.awt.Font("맑은 고딕", 0, 15)); // NOI18N
        SchoolConfirm.setText("학교 인증");
        SchoolConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SchoolConfirmActionPerformed(evt);
            }
        });

        ChangePW.setFont(new java.awt.Font("맑은 고딕", 0, 15)); // NOI18N
        ChangePW.setText("비밀번호 변경");
        ChangePW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePWActionPerformed(evt);
            }
        });

        ChangeEmail.setFont(new java.awt.Font("맑은 고딕", 0, 15)); // NOI18N
        ChangeEmail.setText("정보 변경");
        ChangeEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeEmailActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("맑은 고딕", 0, 15)); // NOI18N
        jLabel4.setText("[앱 설정]");

        Logout.setFont(new java.awt.Font("맑은 고딕", 0, 15)); // NOI18N
        Logout.setText("로그아웃");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        UserDelete.setFont(new java.awt.Font("맑은 고딕", 0, 15)); // NOI18N
        UserDelete.setText("회원 탈퇴");

        jLabel5.setFont(new java.awt.Font("맑은 고딕", 0, 15)); // NOI18N
        jLabel5.setText("[기타]");

        Back.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        Back.setText("뒤로가기");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        PremiumSet.setFont(new java.awt.Font("맑은 고딕", 0, 15)); // NOI18N
        PremiumSet.setText("프리미엄");
        PremiumSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PremiumSetActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("맑은 고딕", 0, 15)); // NOI18N
        jButton1.setText("본인 게시글");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("신고");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Logout)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(UserDelete)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Back)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(ChangeEmail)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ChangePW)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(SchoolConfirm)))))
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(PremiumSet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(Back))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChangePW)
                    .addComponent(ChangeEmail)
                    .addComponent(SchoolConfirm))
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PremiumSet)
                    .addComponent(jButton1))
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserDelete)
                    .addComponent(Logout)
                    .addComponent(jButton2))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        new MainPageController().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_BackActionPerformed

    private void ChangeEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeEmailActionPerformed
        InfoChangeController IC = new InfoChangeController();
        IC.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangeEmailActionPerformed

    private void ChangePWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePWActionPerformed
        PWChangeController PC = new PWChangeController();
        PC.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangePWActionPerformed

    private void SchoolConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SchoolConfirmActionPerformed
        SchoolConfirmController SC = new SchoolConfirmController();
        SC.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_SchoolConfirmActionPerformed

    private void PremiumSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PremiumSetActionPerformed
        PremiumSetController PS = new PremiumSetController();
        PS.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_PremiumSetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        UserPostController UP = new UserPostController();
        UP.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // 사용자 - 로그아웃
        userinfo.UserNum = "00000";
        dispose();
        new LoginController().setVisible(true);
    }//GEN-LAST:event_LogoutActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton ChangeEmail;
    private javax.swing.JButton ChangePW;
    private javax.swing.JButton Logout;
    private javax.swing.JButton PremiumSet;
    private javax.swing.JButton SchoolConfirm;
    private javax.swing.JButton UserDelete;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
